#:schema ./vrsn.json
files = ['VERSION', 'package.json']
verbose = true

[bump]
commit = true
commit-msg = 'bump version to {{.Version}}'
git-tag = false
tag-msg = 'Release {{.Version}}'

[check]
base-branch = 'something-other-than-main'
