name: goreleaser

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git config --global user.email tx3stn@github-action.com
      - run: git config --global user.name 'tx3stn github actions'
      - run: make push-tag
      - run: git fetch --force --tags
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24
          cache: true
      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
